### PR TITLE
Update: Install CUDA (GPUs on Linux) cuDNN version

### PR DESCRIPTION
**Pull request by kruftindustries**
tensorflow_gpu-1.3.0-cp27-cp27mu-manylinux1_x86_64.whl is built against cuDNN v6 now. This would break the install when using:
 pip install tensorflow-gpu 
following this guide. Also added a note to link cuda default install directory to /usr/local/cuda

### CODE REVIEW

**Comment by sunway513** [comment]
@kruftindustries , thanks for the contribution!
However, hipTF was forked from Tensorflow 1.0.1 release; in this context, we should not change any document or software version for the CUDA backend. 
We are working on the upstreaming of hipTF, your concerns will be address there.

**Comment by kruftindustries** [comment]
Ah I see that now. Can you point me to the "how to" specifics for getting tensorflow to use my fiji's and vega's on the ROCm kernel? I am not having success with this

**Comment by sunway513** [comment]
Sure, please review those documents for ROCm:
[https://github.com/ROCmSoftwarePlatform/hiptensorflow/tree/hip/rocm_docs](https://github.com/ROCmSoftwarePlatform/hiptensorflow/tree/hip/rocm_docs)

**Comment by kruftindustries** [comment]
Thank you very much!

**Pull request closed without merging**
